### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by trestea** [xiaoluoge11/lmanager#5]
执行到Python manage.py syncdb 的时候报错。请问什么问题。
如下：
python manage.py syncdb 

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib64/python2.6/site-packages/django/core/management/**init**.py", line 399, in execute_from_command_line
    utility.execute()
  File "/usr/lib64/python2.6/site-packages/django/core/management/**init**.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib64/python2.6/site-packages/django/core/management/**init**.py", line 261, in fetch_command
    commands = get_commands()
  File "/usr/lib64/python2.6/site-packages/django/core/management/**init**.py", line 107, in get_commands
    apps = settings.INSTALLED_APPS
  File "/usr/lib64/python2.6/site-packages/django/conf/**init**.py", line 54, in **getattr**
    self._setup(name)
  File "/usr/lib64/python2.6/site-packages/django/conf/__init__.py", line 49, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/lib64/python2.6/site-packages/django/conf/__init__.py", line 128, in **init**
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib64/python2.6/site-packages/django/utils/importlib.py", line 40, in import_module
    **import**(name)
  File "/data/ops/CMDB/CMDB/settings.py", line 3, in <module>
    mysql = dbconfig() 
  File "/data/ops/CMDB/CMDB/settings_config.py", line 6, in dbconfig
    db_host = cf.get("db","db_host")
  File "/usr/lib64/python2.6/ConfigParser.py", line 556, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'db'

**Comment by xiaoluoge11** [comment]
应该是数据库账号密码权限设置问题，，这个项目Bug太多，目前暂停了，到时候会出新的

At 2016-03-15 16:37:09, "trestea" notifications@github.com wrote:

执行到Python manage.py syncdb 的时候报错。请问什么问题。
如下：
python manage.py syncdb

Traceback (most recent call last):
File "manage.py", line 10, in
execute_from_command_line(sys.argv)
File "/usr/lib64/python2.6/site-packages/django/core/management/init.py", line 399, in execute_from_command_line
utility.execute()
File "/usr/lib64/python2.6/site-packages/django/core/management/init.py", line 392, in execute
self.fetch_command(subcommand).run_from_argv(self.argv)
File "/usr/lib64/python2.6/site-packages/django/core/management/init.py", line 261, in fetch_command
commands = get_commands()
File "/usr/lib64/python2.6/site-packages/django/core/management/init.py", line 107, in get_commands
apps = settings.INSTALLED_APPS
File "/usr/lib64/python2.6/site-packages/django/conf/init.py", line 54, in getattr
self.setup(name)
File "/usr/lib64/python2.6/site-packages/django/conf/__init_.py", line 49, in setup
self.wrapped = Settings(settings_module)
File "/usr/lib64/python2.6/site-packages/django/conf/__init.py", line 128, in init
mod = importlib.import_module(self.SETTINGS_MODULE)
File "/usr/lib64/python2.6/site-packages/django/utils/importlib.py", line 40, in import_module
import(name)
File "/data/ops/CMDB/CMDB/settings.py", line 3, in
mysql = dbconfig()
File "/data/ops/CMDB/CMDB/settings_config.py", line 6, in dbconfig
db_host = cf.get("db","db_host")
File "/usr/lib64/python2.6/ConfigParser.py", line 556, in get
raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'db'

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/xiaoluoge11/lmanager/issues/5

**Comment by trestea** [comment]
大概什么时间，现在正在学习中， 能不能把你的思路，画个流程。

yaya200514@126.com

发件人： 罗辉
发送时间： 2016-03-15 16:48
收件人： xiaoluoge11/lmanager
抄送： trestea
主题： Re: [lmanager] 安装问题 (#5)
应该是数据库账号密码权限设置问题，，这个项目Bug太多，目前暂停了，到时候会出新的

At 2016-03-15 16:37:09, "trestea" notifications@github.com wrote:

执行到Python manage.py syncdb 的时候报错。请问什么问题。
如下：
python manage.py syncdb

Traceback (most recent call last):
File "manage.py", line 10, in
execute_from_command_line(sys.argv)
File "/usr/lib64/python2.6/site-packages/django/core/management/init.py", line 399, in execute_from_command_line
utility.execute()
File "/usr/lib64/python2.6/site-packages/django/core/management/init.py", line 392, in execute
self.fetch_command(subcommand).run_from_argv(self.argv)
File "/usr/lib64/python2.6/site-packages/django/core/management/init.py", line 261, in fetch_command
commands = get_commands()
File "/usr/lib64/python2.6/site-packages/django/core/management/init.py", line 107, in get_commands
apps = settings.INSTALLED_APPS
File "/usr/lib64/python2.6/site-packages/django/conf/init.py", line 54, in getattr
self.setup(name)
File "/usr/lib64/python2.6/site-packages/django/conf/__init_.py", line 49, in setup
self.wrapped = Settings(settings_module)
File "/usr/lib64/python2.6/site-packages/django/conf/__init.py", line 128, in init
mod = importlib.import_module(self.SETTINGS_MODULE)
File "/usr/lib64/python2.6/site-packages/django/utils/importlib.py", line 40, in import_module
import(name)
File "/data/ops/CMDB/CMDB/settings.py", line 3, in
mysql = dbconfig()
File "/data/ops/CMDB/CMDB/settings_config.py", line 6, in dbconfig
db_host = cf.get("db","db_host")
File "/usr/lib64/python2.6/ConfigParser.py", line 556, in get
raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'db'

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/xiaoluoge11/lmanager/issues/5

**Comment by liyingchunvip** [comment]
salt-config明明有这下面这个属性，却提示找不到。请问何解？
Traceback (most recent call last):
  File "salt_event_to_mysql.py", line 8, in <module>
    import salt.config
  File "/usr/local/python27/lib/python2.7/site-packages/salt/config/**init**.py", line 37, in <module>
    import salt.syspaths
  File "/usr/local/python27/lib/python2.7/site-packages/salt/syspaths.py", line 117, in <module>
    SPM_PILLAR_PATH = __generated_syspaths.SPM_PILLAR_PATH
AttributeError: 'module' object has no attribute 'SPM_PILLAR_PATH'

**Comment by liyingchunvip** [comment]
运行命令：nohup python salt_event_to_mysql.py &
还请帮忙解决一下。谢谢
Traceback (most recent call last):
  File "salt_event_to_mysql.py", line 8, in <module>
    import salt.config
  File "/usr/local/python27/lib/python2.7/site-packages/salt/config/**init**.py", line 37, in <module>
    import salt.syspaths
  File "/usr/local/python27/lib/python2.7/site-packages/salt/syspaths.py", line 117, in <module>
    SPM_PILLAR_PATH = __generated_syspaths.SPM_PILLAR_PATH
AttributeError: 'module' object has no attribute 'SPM_PILLAR_PATH'

当前python的模块下有这个配置
[root@jtcrtvdra03 backend]# grep -ri ^SPM_PILLAR_PATH /usr/local/python27/lib/python2.7/site-packages/salt/syspaths.py
SPM_PILLAR_PATH = __generated_syspaths.SPM_PILLAR_PATH

**Comment by xiaoluoge11** [comment]
你好，这个项目是很早之前做的；具体的监听事件可以参考一下地址先做好测试：
http://www.saltstack.cn/kb/saltstack_master_retuner_over_event_system/#saltstack_master_retuner_over_event_system

在 2016-09-20 11:13:32，"liyingchunvip" notifications@github.com 写道：

运行命令：nohup python salt_event_to_mysql.py &
还请帮忙解决一下。谢谢
Traceback (most recent call last):
File "salt_event_to_mysql.py", line 8, in
import salt.config
File "/usr/local/python27/lib/python2.7/site-packages/salt/config/init.py", line 37, in
import salt.syspaths
File "/usr/local/python27/lib/python2.7/site-packages/salt/syspaths.py", line 117, in
SPM_PILLAR_PATH = __generated_syspaths.SPM_PILLAR_PATH
AttributeError: 'module' object has no attribute 'SPM_PILLAR_PATH'

当前python的模块下有这个配置
[root@jtcrtvdra03 backend]# grep -ri ^SPM_PILLAR_PATH /usr/local/python27/lib/python2.7/site-packages/salt/syspaths.py
SPM_PILLAR_PATH = __generated_syspaths.SPM_PILLAR_PATH

**Comment by trestea** [comment]
你好：
新版本时候 出来

yaya200514@126.com

发件人： 罗辉
发送时间： 2016-09-20 11:28
收件人： xiaoluoge11/lmanager
抄送： trestea; Author
主题： Re: [xiaoluoge11/lmanager] 安装问题 (#5)

你好，这个项目是很早之前做的；具体的监听事件可以参考一下地址先做好测试：
http://www.saltstack.cn/kb/saltstack_master_retuner_over_event_system/#saltstack_master_retuner_over_event_system

在 2016-09-20 11:13:32，"liyingchunvip" notifications@github.com 写道：

运行命令：nohup python salt_event_to_mysql.py &
还请帮忙解决一下。谢谢
Traceback (most recent call last):
File "salt_event_to_mysql.py", line 8, in
import salt.config
File "/usr/local/python27/lib/python2.7/site-packages/salt/config/init.py", line 37, in
import salt.syspaths
File "/usr/local/python27/lib/python2.7/site-packages/salt/syspaths.py", line 117, in
SPM_PILLAR_PATH = __generated_syspaths.SPM_PILLAR_PATH
AttributeError: 'module' object has no attribute 'SPM_PILLAR_PATH'

当前python的模块下有这个配置
[root@jtcrtvdra03 backend]# grep -ri ^SPM_PILLAR_PATH /usr/local/python27/lib/python2.7/site-packages/salt/syspaths.py
SPM_PILLAR_PATH = __generated_syspaths.SPM_PILLAR_PATH

**Comment by xiaoluoge11** [comment]
https://github.com/roncoo/roncoo-cmdb

在 2016-09-20 11:37:09，"trestea" notifications@github.com 写道：
你好：
新版本时候 出来

yaya200514@126.com

发件人： 罗辉
发送时间： 2016-09-20 11:28
收件人： xiaoluoge11/lmanager
抄送： trestea; Author
主题： Re: [xiaoluoge11/lmanager] 安装问题 (#5)

你好，这个项目是很早之前做的；具体的监听事件可以参考一下地址先做好测试：
http://www.saltstack.cn/kb/saltstack_master_retuner_over_event_system/#saltstack_master_retuner_over_event_system

在 2016-09-20 11:13:32，"liyingchunvip" notifications@github.com 写道：

运行命令：nohup python salt_event_to_mysql.py &
还请帮忙解决一下。谢谢
Traceback (most recent call last):
File "salt_event_to_mysql.py", line 8, in
import salt.config
File "/usr/local/python27/lib/python2.7/site-packages/salt/config/init.py", line 37, in
import salt.syspaths
File "/usr/local/python27/lib/python2.7/site-packages/salt/syspaths.py", line 117, in
SPM_PILLAR_PATH = __generated_syspaths.SPM_PILLAR_PATH
AttributeError: 'module' object has no attribute 'SPM_PILLAR_PATH'

当前python的模块下有这个配置
[root@jtcrtvdra03 backend]# grep -ri ^SPM_PILLAR_PATH /usr/local/python27/lib/python2.7/site-packages/salt/syspaths.py
SPM_PILLAR_PATH = __generated_syspaths.SPM_PILLAR_PATH
